#
# Fake Identity Generator
# Copyright (C) 2011-2016 Hibbard M. Engler (Bitcoin address 1ERDHsxtekdh5FAsxdb92PBFK7nnuwMkbp for gifts)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
../common/m001.txt:	../common/l013.txt
	time field <../common/l013.txt 100 100 100 100 100 100 100 100 100 100 \
		75 34 33 35 36 7 8 9 10 11 12 13 14 15 16 40 41 42 20 21 22 \
		 23 24 25 74 27 28 30 31 43 44 45 39 50 51 52 53 54 55 56 57 \
		58 59 60 61 62 63 64 65 66 67 68 69 70 71 76 100 100 100 100 100 100 100 100 100 | \
		 fsort 25000000000 >../common/mm1.txt
	mv ../common/mm1.txt ../common/m001.txt


