#
# Fake Identity Generator
# Copyright (C) 2011-2016 Hibbard M. Engler (Bitcoin address 1ERDHsxtekdh5FAsxdb92PBFK7nnuwMkbp for gifts)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# -* city_state - increase the indexes from 5 to 7
# -* Address - increase from 3 to 5
# -* add index after street name is added 
# -* find out why we have so many people living in so few houses///  Example http://10.10.11.9:8889/cs/Palo%20Alto/CA/Middlefield/Middlefield%20Rd/3115
# -* Make the index have Rd - shortened names for the address,  but show up different in the real one. Already done.
# -* nino - need full nino numb er on the last link
# -* Phone number - every search on first area code brings up 202?
# -* state/City - Name/A? WTF?
# -* state/city clean up similar to city./state
# zip - need address like city state
	
	
system:	\
	../out/mobile.txt \
	../out/n001_city_state.txt.m00 \
	../out/n001_city_state.txt.m00.l01 \
	../out/n001_city_state.txt.m00.l01 \
	../out/n001_city_state.txt.m00.l02 \
	../out/n001_city_state.txt.m00.l03 \
	../out/n001_city_state.txt.m00.l04 \
	../out/n001_city_state.txt.m00.l05 \
	../out/n001_city_state.txt.m02 \
	../out/n001_city_state.txt.m02.l01 \
	../out/n001_city_state.txt.m02.l02 \
	../out/n001_city_state.txt.m02.l03 \
	../out/n001_city_state.txt.m02.l04 \
	../out/n001_city_state.txt.m02.l05 \
	../out/n001_city_state.txt.m03 \
	../out/n001_city_state.txt.m04 \
	../out/n001_phone_area_code.txt.m00 \
	../out/n001_phone_area_code.txt.m00.l01 \
	../out/n001_phone_area_code.txt.m00.l02 \
	../out/n001_phone_area_code.txt.m01 \
	../out/n001_phone_area_code.txt.m01.l01 \
	../out/n001_phone_area_code.txt.m01.l02 \
	../out/n001_phone_area_code.txt.m02 \
	../out/n001_phone_area_code.txt.m02.l01 \
	../out/n001_phone_area_code.txt.m02.l02 \
	../out/n001_phone_area_code.txt.m02.l03 \
	../out/n001_phone_area_code.txt.m02.l04 \
	../out/n001_phone_area_code.txt.m02.l05 \
	../out/n001_phone_prefix.txt.m00 \
	../out/n001_phone_prefix.txt.m01 \
	../out/n001_phone_prefix.txt.m02.l01 \
	../out/n001_phone_prefix.txt.m02.l02 \
	../out/n001_phone_prefix.txt.m02 \
	../out/n001_zip_street.txt.m00 \
	../out/n001_zip_street.txt.m00.l01 \
	../out/n001_zip_street.txt.m00.l02 \
	../out/n001_zip_street.txt.m01 \
	../out/n001_zip_street.txt.m01.l01 \
	../out/n001_zip_street.txt.m02 \
	../out/n001_zip_street.txt.m03 \
	../out/n001_zip_street.txt.m04 \
	../out/n001_zip_street.txt.m05 \
	../out/n001_zip_street.txt.m06 \
	../out/n001_first_last_middle.txt.m00 \
	../out/n001_first_last_middle.txt.m00.l01 \
	../out/n001_first_last_middle.txt.m00.l02 \
	../out/n001_first_last_middle.txt.m00.l03 \
	../out/n001_first_last_middle.txt.m01 \
	../out/n001_first_last_middle.txt.m01.l01 \
	../out/n001_first_last_middle.txt.m01.l02 \
	../out/n001_first_last_middle.txt.m01.l03 \
	../out/n001_first_middle_last.txt.m00 \
	../out/n001_first_middle_last.txt.m00.l01 \
	../out/n001_first_middle_last.txt.m00.l02 \
	../out/n001_first_middle_last.txt.m00.l03 \
	../out/n001_first_middle_last.txt.m01 \
	../out/n001_first_middle_last.txt.m01.l01 \
	../out/n001_first_middle_last.txt.m01.l02 \
	../out/n001_first_middle_last.txt.m01.l03 \
	../out/n001_last_first_middle.txt.m00 \
	../out/n001_last_first_middle.txt.m00.l01 \
	../out/n001_last_first_middle.txt.m00.l02 \
	../out/n001_last_first_middle.txt.m00.l03 \
	../out/n001_last_first_middle.txt.m01 \
	../out/n001_last_first_middle.txt.m01.l01 \
	../out/n001_last_first_middle.txt.m01.l02 \
	../out/n001_last_first_middle.txt.m01.l03 \
	../out/n001_nino.txt.m00 \
	../out/n001_nino.txt.m00.l01 \
	../out/n001_nino.txt.m00.l02 \
	../out/n001_nino.txt.m00.l03 \
	../out/n001_nino.txt.m00.l04 \
	../out/n001_nino.txt.m00.l05 \
	../out/n001_nino.txt.m00.l06 \
	../out/n001_nino.txt.m00.l07 \
	../out/n001_nino.txt.m00.l08 \
	 ../out/n001_zip_name.txt \
	../out/n001_id.txt \
	everything
	
everything:	../out/n001_everything.txt \
	../out/n001_everything.txt.m00 
	touch everything

../out/n001_id.txt: ../out/n001.txt 
	field -n 11 <../out/n001.txt | add_id >../out/t65.txt
	mv ../out/t65.txt ../out/n001_id.txt

../out/n001_everything.txt:	../out/n001_last_first_middle.txt  	../out/n001_city_state.txt \
	../out/n001_zip_street.txt ../out/n001_zip4_street.txt ../out/n001_zip_name.txt ../out/n001_city_state.txt \
	../out/n001_phone_area_code.txt ../out/n001_phone_prefix.txt \
	../out/n001_nino.txt ../out/n001_dl.txt ../out/n001_passport.txt \
	../out/n001_first_last_middle.txt \
	 ../out/n001_first_middle_last.txt
	 bash ./make_everything.sh >../out/e1.txt
	 mv ../out/e1.txt ../out/n001_everything.txt

../out/n001_zip_street.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_zip_street.txt.m00



../out/n001_zip_street.txt.m00.l01: ../out/n001_zip_street.txt
	fielduc -s -l1 2 40000000 <../out/n001_zip_street.txt | add_id > ../out/zak19.txt
	mv ../out/zak19.txt ../out/n001_zip_street.txt.m00.l01

../out/n001_zip_street.txt.m00.l02: ../out/n001_zip_street.txt
	fielduc -s -l2 2 40000000 <../out/n001_zip_street.txt | add_id > ../out/zak219.txt
	mv ../out/zak219.txt ../out/n001_zip_street.txt.m00.l02

../out/n001_zip_street.txt.m01: ../out/n001_zip_street.txt
	fielduc 2  -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1.txt
	mv ../out/zab1.txt ../out/n001_zip_street.txt.m01

../out/n001_zip_street.txt.m01.l01: ../out/n001_zip_street.txt
	fielduc -s  2 -l1 3 40000000 <../out/n001_zip_street.txt | add_id > ../out/zak19s.txt
	mv ../out/zak19s.txt ../out/n001_zip_street.txt.m01.l01

../out/n001_zip_street.txt.m02: ../out/n001_zip_street.txt
	fielduc 2 3 -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1x2.txt
	mv ../out/zab1x2.txt ../out/n001_zip_street.txt.m02

../out/n001_zip_street.txt.m03: ../out/n001_zip_street.txt
	fielduc 2 3 4 -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1x3.txt
	mv ../out/zab1x3.txt ../out/n001_zip_street.txt.m03

../out/n001_zip_street.txt.m04: ../out/n001_zip_street.txt
	fielduc 2 3 4 5 -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1x4.txt
	mv ../out/zab1x4.txt ../out/n001_zip_street.txt.m04
	
../out/n001_zip_street.txt.m05: ../out/n001_zip_street.txt
	fielduc 2 3 4 5 6 -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1x5.txt
	mv ../out/zab1x5.txt ../out/n001_zip_street.txt.m05
	
../out/n001_zip_street.txt.m06: ../out/n001_zip_street.txt
	fielduc 2 3 4 5 6 7 -s 40000000 <../out/n001_zip_street.txt |  add_id >../out/zab1x6.txt
	mv ../out/zab1x6.txt ../out/n001_zip_street.txt.m06


	
../out/n001_first_last_middle.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_first_last_middle.txt.m00

../out/n001_first_last_middle.txt.m00.l01: ../out/n001_first_last_middle.txt
	fielduc -s -l1 2 40000000 <../out/n001_first_last_middle.txt | add_id > ../out/k19.txt
	mv ../out/k19.txt ../out/n001_first_last_middle.txt.m00.l01

../out/n001_first_last_middle.txt.m00.l02: ../out/n001_first_last_middle.txt
	fielduc -s -l2 2 40000000 <../out/n001_first_last_middle.txt | add_id >../out/k12.txt
	mv ../out/k12.txt ../out/n001_first_last_middle.txt.m00.l02
	
../out/n001_first_last_middle.txt.m00.l03: ../out/n001_first_last_middle.txt
	fielduc -s -l3 2 40000000 <../out/n001_first_last_middle.txt | add_id >../out/k14.txt
	mv ../out/k14.txt ../out/n001_first_last_middle.txt.m00.l03

../out/n001_first_last_middle.txt.m00.l04: ../out/n001_first_last_middle.txt
	fielduc -s -l4 2 40000000 <../out/n001_first_last_middle.txt | add_id >../out/k14e.txt
	mv ../out/k14e.txt ../out/n001_first_last_middle.txt.m00.l04

../out/n001_first_last_middle.txt.m00.l05: ../out/n001_first_last_middle.txt
	fielduc -s -l5 2 40000000 <../out/n001_first_last_middle.txt | add_id >../out/k14f.txt
	mv ../out/k14f.txt ../out/n001_first_last_middle.txt.m00.l05
	
../out/n001_first_last_middle.txt.m01: ../out/n001_first_last_middle.txt
	fielduc 2  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1.txt
	mv ../out/b1.txt ../out/n001_first_last_middle.txt.m01

../out/n001_first_last_middle.txt.m01.l01: ../out/n001_first_last_middle.txt
	fielduc 2 -l1 3  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1q.txt
	mv ../out/b1q.txt ../out/n001_first_last_middle.txt.m01.l01

../out/n001_first_last_middle.txt.m01.l02: ../out/n001_first_last_middle.txt
	fielduc 2 -l2 3  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1q2.txt
	mv ../out/b1q2.txt ../out/n001_first_last_middle.txt.m01.l02

../out/n001_first_last_middle.txt.m01.l03: ../out/n001_first_last_middle.txt
	fielduc 2 -l3 3  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1q3.txt
	mv ../out/b1q3.txt ../out/n001_first_last_middle.txt.m01.l03
	
../out/n001_first_last_middle.txt.m01.l04: ../out/n001_first_last_middle.txt
	fielduc 2 -l4 3  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1q4.txt
	mv ../out/b1q4.txt ../out/n001_first_last_middle.txt.m01.l04	
	
../out/n001_first_last_middle.txt.m01.l05: ../out/n001_first_last_middle.txt
	fielduc 2 -l5 3  -s 40000000 <../out/n001_first_last_middle.txt |  add_id >../out/b1q5.txt
	mv ../out/b1q5.txt ../out/n001_first_last_middle.txt.m01.l05	
	

../out/n001_state_city_zip.txt:	../out/n001.txt random_seed2
	time fsort -q -d`cat random_seed2` -n 26000000000 <../out/n001.txt >../out/a2.txt \
		24 23 18 38 19 20 39 16 21 22 25
	mv ../out/a2.txt ../out/n001_state_city_zip.txt

		

../out/n001_first_middle_last.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_first_middle_last.txt.m00

../out/n001_first_middle_last.txt.m00.l01: ../out/n001_first_middle_last.txt
	fielduc -s -l1 2 40000000 <../out/n001_first_middle_last.txt | add_id > ../out/c19.txt
	mv ../out/c19.txt ../out/n001_first_middle_last.txt.m00.l01

../out/n001_first_middle_last.txt.m00.l02: ../out/n001_first_middle_last.txt
	fielduc -s -l2 2 40000000 <../out/n001_first_middle_last.txt | add_id >../out/c12.txt
	mv ../out/c12.txt ../out/n001_first_middle_last.txt.m00.l02
	
../out/n001_first_middle_last.txt.m00.l03: ../out/n001_first_middle_last.txt
	fielduc -s -l3 2 40000000 <../out/n001_first_middle_last.txt | add_id >../out/c14.txt
	mv ../out/c14.txt ../out/n001_first_middle_last.txt.m00.l03

../out/n001_first_middle_last.txt.m00.l04: ../out/n001_first_middle_last.txt
	fielduc -s -l4 2 40000000 <../out/n001_first_middle_last.txt | add_id >../out/c14e.txt
	mv ../out/c14e.txt ../out/n001_first_middle_last.txt.m00.l04

../out/n001_first_middle_last.txt.m00.l05: ../out/n001_first_middle_last.txt
	fielduc -s -l5 2 40000000 <../out/n001_first_middle_last.txt | add_id >../out/c14f.txt
	mv ../out/c14f.txt ../out/n001_first_middle_last.txt.m00.l05
	
../out/n001_first_middle_last.txt.m01: ../out/n001_first_middle_last.txt
	fielduc 2  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1.txt
	mv ../out/c1.txt ../out/n001_first_middle_last.txt.m01

../out/n001_first_middle_last.txt.m01.l01: ../out/n001_first_middle_last.txt
	fielduc 2 -l1 3  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1q.txt
	mv ../out/c1q.txt ../out/n001_first_middle_last.txt.m01.l01

../out/n001_first_middle_last.txt.m01.l02: ../out/n001_first_middle_last.txt
	fielduc 2 -l2 3  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1q2.txt
	mv ../out/c1q2.txt ../out/n001_first_middle_last.txt.m01.l02

../out/n001_first_middle_last.txt.m01.l03: ../out/n001_first_middle_last.txt
	fielduc 2 -l3 3  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1q3.txt
	mv ../out/c1q3.txt ../out/n001_first_middle_last.txt.m01.l03

../out/n001_first_middle_last.txt.m01.l04: ../out/n001_first_middle_last.txt
	fielduc 2 -l4 3  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1q4.txt
	mv ../out/c1q4.txt ../out/n001_first_middle_last.txt.m01.l04

../out/n001_first_middle_last.txt.m01.l05: ../out/n001_first_middle_last.txt
	fielduc 2 -l5 3  -s 40000000 <../out/n001_first_middle_last.txt |  add_id >../out/c1q5.txt
	mv ../out/c1q5.txt ../out/n001_first_middle_last.txt.m01.l05

../out/n001_first_middle_last.txt:	../out/n001.txt random_seed11
	time fsort -q -d`cat random_seed11` -n 26000000000 <../out/n001.txt >../out/a16.txt \
		13 15 12
	mv ../out/a16.txt ../out/n001_first_middle_last.txt








../out/n001_last_first_middle.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_last_first_middle.txt.m00

../out/n001_last_first_middle.txt.m00.l01: ../out/n001_last_first_middle.txt
	fielduc -s -l1 2 40000000 <../out/n001_last_first_middle.txt | add_id > ../out/w19.txt
	mv ../out/w19.txt ../out/n001_last_first_middle.txt.m00.l01

../out/n001_last_first_middle.txt.m00.l02: ../out/n001_last_first_middle.txt
	fielduc -s -l2 2 40000000 <../out/n001_last_first_middle.txt | add_id >../out/w12.txt
	mv ../out/w12.txt ../out/n001_last_first_middle.txt.m00.l02
	
../out/n001_last_first_middle.txt.m00.l03: ../out/n001_last_first_middle.txt
	fielduc -s -l3 2 40000000 <../out/n001_last_first_middle.txt | add_id >../out/w14.txt
	mv ../out/w14.txt ../out/n001_last_first_middle.txt.m00.l03

../out/n001_last_first_middle.txt.m00.l04: ../out/n001_last_first_middle.txt
	fielduc -s -l4 2 40000000 <../out/n001_last_first_middle.txt | add_id >../out/w14e.txt
	mv ../out/w14e.txt ../out/n001_last_first_middle.txt.m00.l04

../out/n001_last_first_middle.txt.m00.l05: ../out/n001_last_first_middle.txt
	fielduc -s -l5 2 40000000 <../out/n001_last_first_middle.txt | add_id >../out/w14f.txt
	mv ../out/w14f.txt ../out/n001_last_first_middle.txt.m00.l05
	
../out/n001_last_first_middle.txt.m01: ../out/n001_last_first_middle.txt
	fielduc 2  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1.txt
	mv ../out/w1.txt ../out/n001_last_first_middle.txt.m01

../out/n001_last_first_middle.txt.m01.l01: ../out/n001_last_first_middle.txt
	fielduc 2 -l1 3  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1q.txt
	mv ../out/w1q.txt ../out/n001_last_first_middle.txt.m01.l01

../out/n001_last_first_middle.txt.m01.l02: ../out/n001_last_first_middle.txt
	fielduc 2 -l2 3  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1q2.txt
	mv ../out/w1q2.txt ../out/n001_last_first_middle.txt.m01.l02

../out/n001_last_first_middle.txt.m01.l03: ../out/n001_last_first_middle.txt
	fielduc 2 -l3 3  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1q3.txt
	mv ../out/w1q3.txt ../out/n001_last_first_middle.txt.m01.l03

../out/n001_last_first_middle.txt.m01.l04: ../out/n001_last_first_middle.txt
	fielduc 2 -l4 3  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1q4.txt
	mv ../out/w1q4.txt ../out/n001_last_first_middle.txt.m01.l04

../out/n001_last_first_middle.txt.m01.l05: ../out/n001_last_first_middle.txt
	fielduc 2 -l5 3  -s 40000000 <../out/n001_last_first_middle.txt |  add_id >../out/w1q5.txt
	mv ../out/w1q5.txt ../out/n001_last_first_middle.txt.m01.l05

../out/n001_last_first_middle.txt:	../out/n001.txt random_seed1
	time fsort -q -d`cat random_seed1` -n 26000000000 <../out/n001.txt >../out/a1.txt \
		12 13 14 15 
	mv ../out/a1.txt ../out/n001_last_first_middle.txt






../out/n001_nino.txt:	../out/n001.txt 
	time fsort -q 26000000000  -n <../out/n001.txt >../out/a10.txt \
		50
	mv ../out/a10.txt ../out/n001_nino.txt

../out/n001_nino.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_nino.txt.m00

../out/n001_nino.txt.m00.l01: ../out/n001_nino.txt
	fielduc -s -l1 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss19.txt
	mv ../out/ss19.txt ../out/n001_nino.txt.m00.l01

../out/n001_nino.txt.m00.l02: ../out/n001_nino.txt
	fielduc -s -l2 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss2.txt
	mv ../out/ss2.txt ../out/n001_nino.txt.m00.l02

../out/n001_nino.txt.m00.l03: ../out/n001_nino.txt
	fielduc -s -l3 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss3.txt
	mv ../out/ss3.txt ../out/n001_nino.txt.m00.l03

../out/n001_nino.txt.m00.l04: ../out/n001_nino.txt
	fielduc -s -l4 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss4.txt
	mv ../out/ss4.txt ../out/n001_nino.txt.m00.l04

../out/n001_nino.txt.m00.l05: ../out/n001_nino.txt
	fielduc -s -l5 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss5.txt
	mv ../out/ss5.txt ../out/n001_nino.txt.m00.l05

../out/n001_nino.txt.m00.l06: ../out/n001_nino.txt
	fielduc -s -l6 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss6.txt
	mv ../out/ss6.txt ../out/n001_nino.txt.m00.l06

../out/n001_nino.txt.m00.l07: ../out/n001_nino.txt
	fielduc -s -l7 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss7.txt
	mv ../out/ss7.txt ../out/n001_nino.txt.m00.l07

../out/n001_nino.txt.m00.l08: ../out/n001_nino.txt
	fielduc -s -l8 2 40000000 <../out/n001_nino.txt | add_id > ../out/ss8.txt
	mv ../out/ss8.txt ../out/n001_nino.txt.m00.l08

../out/n001_city_state.txt:	../out/n001.txt random_seed3
	m_to_address_name -u  <../out/n001.txt  | field 1 2 5 6 7 8 -d`cat random_seed3` |  fsort -q 26000000000  1 2 3 4 5 7 6 >../out/a7.txt
	mv ../out/a7.txt ../out/n001_city_state.txt

../out/n001_city_state.txt.m00: ../out/n001_city_state.txt
	wc -l <../out/n001_city_state.txt | add_id >../out/b0.txt
	mv ../out/b0.txt ../out/n001_city_state.txt.m00

../out/n001_city_state.txt.m00.l01: ../out/n001_city_state.txt
	fielduc -s  -l1 2 40000000 <../out/n001_city_state.txt | add_id >../out/b2.txt
	mv ../out/b2.txt ../out/n001_city_state.txt.m00.l01

../out/n001_city_state.txt.m00.l02: ../out/n001_city_state.txt
	fielduc -s  -l2 2 40000000 <../out/n001_city_state.txt | add_id >../out/b3.txt
	mv ../out/b3.txt ../out/n001_city_state.txt.m00.l02

../out/n001_city_state.txt.m00.l03: ../out/n001_city_state.txt
	fielduc -s  -l3 2 40000000 <../out/n001_city_state.txt | add_id >../out/b6.txt
	mv ../out/b6.txt ../out/n001_city_state.txt.m00.l03

../out/n001_city_state.txt.m00.l04: ../out/n001_city_state.txt
	fielduc -s  -l4 2 40000000 <../out/n001_city_state.txt | add_id >../out/b64.txt
	mv ../out/b64.txt ../out/n001_city_state.txt.m00.l04

../out/n001_city_state.txt.m00.l05: ../out/n001_city_state.txt
	fielduc -s  -l5 2 40000000 <../out/n001_city_state.txt | add_id >../out/b65.txt
	mv ../out/b65.txt ../out/n001_city_state.txt.m00.l05

../out/n001_city_state.txt.m00.l06: ../out/n001_city_state.txt
	fielduc -s  -l6 2 40000000 <../out/n001_city_state.txt | add_id >../out/b66.txt
	mv ../out/b66.txt ../out/n001_city_state.txt.m00.l06

../out/n001_city_state.txt.m00.l07: ../out/n001_city_state.txt
	fielduc -s  -l7 2 40000000 <../out/n001_city_state.txt | add_id >../out/b67.txt
	mv ../out/b67.txt ../out/n001_city_state.txt.m00.l07

../out/n001_city_state.txt.m02: ../out/n001_city_state.txt
	fielduc -s   2 3 40000000 <../out/n001_city_state.txt | add_id >../out/b4.txt
	mv ../out/b4.txt ../out/n001_city_state.txt.m02

../out/n001_city_state.txt.m02.l01: ../out/n001_city_state.txt
	fielduc -s   2 3 -l1 4  40000000 <../out/n001_city_state.txt | add_id >../out/b5q.txt
	mv ../out/b5q.txt ../out/n001_city_state.txt.m02.l01

../out/n001_city_state.txt.m02.l02: ../out/n001_city_state.txt
	fielduc -s   2 3 -l2 4  40000000 <../out/n001_city_state.txt | 	add_id >../out/b6q.txt
	mv ../out/b6q.txt ../out/n001_city_state.txt.m02.l02

../out/n001_city_state.txt.m02.l03: ../out/n001_city_state.txt
	fielduc -s   2 3 -l3 4  40000000 <../out/n001_city_state.txt | 	add_id >../out/b6q3.txt
	mv ../out/b6q3.txt ../out/n001_city_state.txt.m02.l03

../out/n001_city_state.txt.m02.l04: ../out/n001_city_state.txt
	fielduc -s   2 3 -l4 4  40000000 <../out/n001_city_state.txt | 	add_id >../out/b6q4.txt
	mv ../out/b6q4.txt ../out/n001_city_state.txt.m02.l04

../out/n001_city_state.txt.m02.l05: ../out/n001_city_state.txt
	fielduc -s   2 3 -l5 4  40000000 <../out/n001_city_state.txt | 	add_id >../out/b6q5.txt
	mv ../out/b6q5.txt ../out/n001_city_state.txt.m02.l05

../out/n001_city_state.txt.m03: ../out/n001_city_state.txt
	fielduc -s   2 3 4  40000000 <../out/n001_city_state.txt | add_id >../out/b5.txt
	mv ../out/b5.txt ../out/n001_city_state.txt.m03

../out/n001_city_state.txt.m04: ../out/n001_city_state.txt
	fielduc -s   2 3 4 5  40000000 <../out/n001_city_state.txt | add_id >../out/b7.txt
	mv ../out/b7.txt ../out/n001_city_state.txt.m04

../out/n001_city_state.txt.m04.l01: ../out/n001_city_state.txt
	fielduc -s   2 3 4 5 -l1 6  40000000 <../out/n001_city_state.txt | add_id >../out/b7l01.txt
	mv ../out/b7l01.txt ../out/n001_city_state.txt.m04.l01

../out/n001_city_state.txt.m04.l02: ../out/n001_city_state.txt
	fielduc -s   2 3 4 5 -l1 6  40000000 <../out/n001_city_state.txt | add_id >../out/b7l02.txt
	mv ../out/b7l02.txt ../out/n001_city_state.txt.m04.l02


../out/n001_city_state.txt.m05: ../out/n001_city_state.txt
	fielduc -s   2 3 4 5 6 40000000 <../out/n001_city_state.txt | add_id >../out/b7775.txt
	mv ../out/b7775.txt ../out/n001_city_state.txt.m05

../out/n001_zip_street.txt:	../out/n001.txt random_seed4
	time m_to_address_name -u2  <../out/n001.txt  | field  3 4 1 2 5 6 7 8 -d`cat random_seed4` | fsort -q 2500000000  1 2 3 4 5 6 7 9 8 >../out/a4.txt
	mv ../out/a4.txt ../out/n001_zip_street.txt

../out/n001_zip4_street.txt:	../out/n001.txt random_seed5
	time fsort -q 26000000000  -d`cat random_seed5` -n <../out/n001.txt >../out/a5.txt \
		25 30   18 38 19 20 39 16 21 22
	mv ../out/a5.txt ../out/n001_zip4_street.txt

../out/n001_zip_name.txt:	../out/n001.txt random_seed6
	time fsort -q 26000000000  -d`cat random_seed6` -n <../out/n001.txt >../out/a6.txt \
		25 12 29 13 14 15 
	mv ../out/a6.txt ../out/n001_zip_name.txt




 ../out/n001_phone_area_code.txt:	../out/n001.txt 
	echo "phone setup"
	m_to_phone -u <../out/n001.txt | fsort -q 16000000000 >../out/a8.txt
	mv ../out/a8.txt  ../out/n001_phone_area_code.txt

../out/n001_phone_area_code.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_phone_area_code.txt.m00

../out/n001_phone_area_code.txt.m00.l01: ../out/n001_phone_area_code.txt
	fielduc -s -l1 2 <../out/n001_phone_area_code.txt | add_id  >../out/u22l01.txt
	mv ../out/u22l01.txt ../out/n001_phone_area_code.txt.m00.l01

../out/n001_phone_area_code.txt.m00.l02: ../out/n001_phone_area_code.txt
	fielduc -s -l2 2 <../out/n001_phone_area_code.txt | add_id  >../out/u22l02.txt
	mv ../out/u22l02.txt ../out/n001_phone_area_code.txt.m00.l02

../out/n001_phone_area_code.txt.m01: ../out/n001_phone_area_code.txt
	fielduc -s 2 <../out/n001_phone_area_code.txt | add_id  >../out/u22.txt
	mv ../out/u22.txt ../out/n001_phone_area_code.txt.m01

../out/n001_phone_area_code.txt.m01.l01: ../out/n001_phone_area_code.txt
	fielduc -s 2 -l1 3 <../out/n001_phone_area_code.txt | add_id  >../out/u22l01x.txt
	mv ../out/u22l01x.txt ../out/n001_phone_area_code.txt.m01.l01

../out/n001_phone_area_code.txt.m01.l02: ../out/n001_phone_area_code.txt
	fielduc -s 2 -l2 3 <../out/n001_phone_area_code.txt | add_id  >../out/u22l02x.txt
	mv ../out/u22l02x.txt ../out/n001_phone_area_code.txt.m01.l02

../out/n001_phone_area_code.txt.m02: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 <../out/n001_phone_area_code.txt | add_id >../out/u23.txt
	mv ../out/u23.txt ../out/n001_phone_area_code.txt.m02

../out/n001_phone_area_code.txt.m02.l01: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 -l1 4 40000000 <../out/n001_phone_area_code.txt | add_id >../out/u53.txt
	mv ../out/u53.txt ../out/n001_phone_area_code.txt.m02.l01

../out/n001_phone_area_code.txt.m02.l02: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 -l2 4 40000000 <../out/n001_phone_area_code.txt | add_id >../out/u532.txt
	mv ../out/u532.txt ../out/n001_phone_area_code.txt.m02.l02

../out/n001_phone_area_code.txt.m02.l03: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 -l3 4 40000000 <../out/n001_phone_area_code.txt | add_id >../out/u533.txt
	mv ../out/u533.txt ../out/n001_phone_area_code.txt.m02.l03

../out/n001_phone_area_code.txt.m02.l04: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 -l4 4 40000000 <../out/n001_phone_area_code.txt | add_id >../out/u534.txt
	mv ../out/u534.txt ../out/n001_phone_area_code.txt.m02.l04

../out/n001_phone_area_code.txt.m02.l05: ../out/n001_phone_area_code.txt
	fielduc -s 2 3 -l5 4 40000000 <../out/n001_phone_area_code.txt | add_id >../out/u535.txt
	mv ../out/u535.txt ../out/n001_phone_area_code.txt.m02.l05

	
../out/n001_phone_prefix.txt:	../out/n001.txt random_seed9
	echo "phone prefix setup"
	m_to_phone_prefix -u <../out/n001.txt | fsort -q 21000000000 >../out/mp8.txt
	mv ../out/mp8.txt ../out/n001_phone_prefix.txt

../out/n001_phone_prefix.txt.m00: ../out/n001_city_state.txt.m00
	cp ../out/n001_city_state.txt.m00 ../out/n001_phone_prefix.txt.m00

../out/n001_phone_prefix.txt.m01: ../out/n001_phone_prefix.txt
	fielduc -s 2 <../out/n001_phone_prefix.txt | add_id  >../out/mp2.txt
	mv ../out/mp2.txt ../out/n001_phone_prefix.txt.m01

../out/n001_phone_prefix.txt.m02: ../out/n001_phone_prefix.txt
	fielduc -s 2 3 <../out/n001_phone_prefix.txt | add_id >../out/mp3.txt
	mv ../out/mp3.txt ../out/n001_phone_prefix.txt.m02

../out/n001_phone_prefix.txt.m02.l01: ../out/n001_phone_prefix.txt
	fielduc -s 2 3 -l1 4 40000000 <../out/n001_phone_prefix.txt | add_id >../out/mp4.txt
	mv ../out/mp4.txt ../out/n001_phone_prefix.txt.m02.l01


../out/n001_phone_prefix.txt.m02.l02: ../out/n001_phone_prefix.txt
	fielduc -s 2 3 -l2 4 40000000 <../out/n001_phone_prefix.txt | add_id >../out/mp42.txt
	mv ../out/mp42.txt ../out/n001_phone_prefix.txt.m02.l02



../out/n001_dl.txt:	../out/n001.txt 
	time fsort -q 26000000000  -n <../out/n001.txt >../out/a11.txt 51 24
	mv ../out/a11.txt ../out/n001_dl.txt

../out/n001_passport.txt:	../out/n001.txt 
	time fsort -q 26000000000  -n <../out/n001.txt >../out/a17.txt \
		61
	mv ../out/a17.txt ../out/n001_passport.txt

../out/n001_first_last_middle.txt:	../out/n001.txt random_seed11
	time fsort -q -d`cat random_seed11` -n 26000000000 <../out/n001.txt >../out/a15.txt \
		13 12 14 15 
	mv ../out/a15.txt ../out/n001_first_last_middle.txt

	
random_seed1:
	generate_random_seed >random_seed1

random_seed2:
	generate_random_seed >random_seed2

random_seed3:
	generate_random_seed >random_seed3

random_seed4:
	generate_random_seed >random_seed4

random_seed5:
	generate_random_seed >random_seed5

random_seed6:
	generate_random_seed >random_seed6

random_seed7:
	generate_random_seed >random_seed7

random_seed8:
	generate_random_seed >random_seed8

random_seed9:
	generate_random_seed >random_seed9

random_seed10:
	generate_random_seed >random_seed10

random_seed11:
	generate_random_seed >random_seed11
	
	
	
	
	
	


../out/n001_everything.txt.m00: ../out/n001_everything.txt
	wc -l <../out/n001_everything.txt | add_id >../out/gb0.txt
	mv ../out/gb0.txt ../out/n001_everything.txt.m00

../out/mobile.txt: ../../out/mobile.txt
	cp ../../out/mobile.txt ../out/mobile.txt
	
	
	
