/*
Fake Identity Generator
Copyright (C) 2011-2016 Hibbard M. Engler (Bitcoin address 1ERDHsxtekdh5FAsxdb92PBFK7nnuwMkbp for gifts)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/
/* probably for the evercookie which is not fully implemented */

/* add plugin detect logic */
"char *fingerprint(char *buf) {\n"
"char *e;\n"
"/* PluginDetect yeah [ onWindowLoaded getVersion Java(OTF&getInfo) QT DevalVR Shockwave Flash WMP Silverlight VLC ] by Eric Gerds www.pinlady.net/PluginDetect */ if(!PluginDetect){var PluginDetect={getNum:function(b,c){if(!this.num(b)){return null\n"
"}var a;\n"
"if(typeof c==\"undefined\"){a=/[\d][\d\.\_,-]*/.exec(b)\n"
"}else{a=(new RegExp(c)).exec(b)\n"
"}return a?a[0].replace(/[\.\_-]/g,\",\"):null\n"
"},hasMimeType:function(c){if(PluginDetect.isIE){return null\n"
"}var b,a,d,e=c.constructor==String?[c]:c;\n"
"for(d=0;\n"
"d<e.length;\n"
"d++){b=navigator.mimeTypes[e[d]];\n"
"if(b&&b.enabledPlugin){a=b.enabledPlugin;\n"
"if(a.name||a.description){return b\n"
"}}}return null\n"
"},findNavPlugin:function(g,d){var a=g.constructor==String?g:g.join(\".*\"),e=d===false?\"\":\"\\d\",b,c=new RegExp(a+\".*\"+e+\"|\"+e+\".*\"+a,\"i\"),f=navigator.plugins;\n"
"for(b=0;\n"
"b<f.length;\n"
"b++){if(c.test(f[b].description)||c.test(f[b].name)){return f[b]\n"
"}}return null\n"
"},AXO:window.ActiveXObject,getAXO:function(b,a){var f=null,d,c=false;\n"
"try{f=new this.AXO(b);\n"
"c=true\n"
"}catch(d){}if(typeof a!=\"undefined\"){delete f;\n"
"return c\n"
"}return f\n"
"},num:function(a){return(typeof a!=\"string\"?false:(/\d/).test(a))\n"
"},compareNums:function(g,e){var d=this,c,b,a,f=window.parseInt;\n"
"if(!d.num(g)||!d.num(e)){return 0\n"
"}if(d.plugin&&d.plugin.compareNums){return d.plugin.compareNums(g,e)\n"
"}c=g.split(\",\");\n"
"b=e.split(\",\");\n"
"for(a=0;\n"
"a<Math.min(c.length,b.length);\n"
"a++){if(f(c[a],10)>f(b[a],10)){return 1\n"
"}if(f(c[a],10)<f(b[a],10)){return -1\n"
"}}return 0\n"
"},formatNum:function(b){if(!this.num(b)){return null\n"
"}var a,c=b.replace(/\s/g,\"\").replace(/[\.\_]/g,\",\").split(\",\").concat([\"0\",\"0\",\"0\",\"0\"]);\n"
"for(a=0;\n"
"a<4;\n"
"a++){if(/^(0+)(.+)$/.test(c[a])){c[a]=RegExp.$2\n"
"}}if(!(/\d/).test(c[0])){c[0]=\"0\"\n"
"}return c[0]+\",\"+c[1]+\",\"+c[2]+\",\"+c[3]\n"
"},initScript:function(){var $=this,userAgent=navigator.userAgent;\n"
"$.isIE=\n"
"/*@cc_on!@*/\n"
"false;\n"
"$.IEver=$.isIE&&((/MSIE\s*(\d\.?\d*)/i).exec(userAgent))?parseFloat(RegExp.$1,10):-1;\n"
"$.ActiveXEnabled=false;\n"
"if($.isIE){var x,progid=[\"Msxml2.XMLHTTP\",\"Msxml2.DOMDocument\",\"Microsoft.XMLDOM\",\"ShockwaveFlash.ShockwaveFlash\",\"TDCCtl.TDCCtl\",\"Shell.UIHelper\",\"Scripting.Dictionary\",\"wmplayer.ocx\"];\n"
"for(x=0;\n"
"x<progid.length;\n"
"x++){if($.getAXO(progid[x],1)){$.ActiveXEnabled=true;\n"
"break\n"
"}}$.head=typeof document.getElementsByTagName!=\"undefined\"?document.getElementsByTagName(\"head\")[0]:null\n"
"}$.isGecko=!$.isIE&&typeof navigator.product==\"string\"&&(/Gecko/i).test(navigator.product)&&(/Gecko\s*\/\s*\d/i).test(userAgent)?true:false;\n"
"$.GeckoRV=$.isGecko?$.formatNum((/rv\s*\:\s*([\.\,\d]+)/i).test(userAgent)?RegExp.$1:\"0.9\"):null;\n"
"$.isSafari=!$.isIE&&(/Safari\s*\/\s*\d/i).test(userAgent)?true:false;\n"
"$.isChrome=(/Chrome\s*\/\s*\d/i).test(userAgent)?true:false;\n"
"$.onWindowLoaded(0)\n"
"},init:function(c,a){if(typeof c!=\"string\"){return -3\n"
"}c=c.toLowerCase().replace(/\s/g,\"\");\n"
"var b=this,d;\n"
"if(typeof b[c]==\"undefined\"){return -3\n"
"}d=b[c];\n"
"b.plugin=d;\n"
"if(typeof d.installed==\"undefined\"||a==true){d.installed=null;\n"
"d.version=null;\n"
"d.version0=null;\n"
"d.getVersionDone=null;\n"
"d.$=b\n"
"}b.garbage=false;\n"
"if(b.isIE&&!b.ActiveXEnabled){if(b.plugin!=b.java){return -2\n"
"}}return 1\n"
"},isMinVersion:function(g,e,c,b){\n"
"return -3\n"
"},getVersion:function(e,b,a){\n"
"var d=PluginDetect,c=d.init(e),f;\n"
"if(c<0){return null\n"
"}f=d.plugin;\n"
"if(f.getVersionDone!=1){f.getVersion(b,a);\n"
"if(f.getVersionDone===null){f.getVersionDone=1\n"
"}}d.cleanup();\n"
"return(f.version||f.version0);\n"
";\n"
"return null\n"
"},getInfo:function(f,c,b){var a={};\n"
";\n"
"var e=PluginDetect,d=e.init(f),g;\n"
"if(d<0){return a\n"
"}g=e.plugin;\n"
"if(typeof g.getInfo!=\"undefined\"){if(g.getVersionDone===null){e.getVersion(f,c,b)\n"
"}a=g.getInfo()\n"
"};\n"
"return a\n"
"},cleanup:function(){\n"
"var a=this;\n"
"if(a.garbage&&typeof window.CollectGarbage!=\"undefined\"){window.CollectGarbage()\n"
"}\n"
"},isActiveXObject:function(b){\n"
"var d=this,a,g,f=\"/\",c='<object width=\"1\" height=\"1\" style=\"display:none\" '+d.plugin.getCodeBaseVersion(b)+\">\"+d.plugin.HTML+\"<\"+f+\"object>\";\n"
"if(d.head.firstChild){d.head.insertBefore(document.createElement(\"object\"),d.head.firstChild)\n"
"}else{d.head.appendChild(document.createElement(\"object\"))\n"
"}d.head.firstChild.outerHTML=c;\n"
"try{d.head.firstChild.classid=d.plugin.classID\n"
"}catch(g){}a=false;\n"
"try{if(d.head.firstChild.object){a=true\n"
"}}catch(g){}try{if(a&&d.head.firstChild.readyState<4){d.garbage=true\n"
"}}catch(g){}d.head.removeChild(d.head.firstChild);\n"
"return a;\n"
"\n"
"},codebaseSearch:function(c){var e=this;\n"
"if(!e.ActiveXEnabled){return null\n"
"}if(typeof c!=\"undefined\"){return e.isActiveXObject(c)\n"
"};\n"
"var j=[0,0,0,0],g,f,b=e.plugin.digits,i=function(k,m){var l=(k==0?m:j[0])+\",\"+(k==1?m:j[1])+\",\"+(k==2?m:j[2])+\",\"+(k==3?m:j[3]);\n"
"return e.isActiveXObject(l)\n"
"};\n"
"var h,d,a=false;\n"
"for(g=0;\n"
"g<b.length;\n"
"g++){h=b[g]*2;\n"
"j[g]=0;\n"
"for(f=0;\n"
"f<20;\n"
"f++){if(h==1&&g>0&&a){break\n"
"}if(h-j[g]>1){d=Math.round((h+j[g])/2);\n"
"if(i(g,d)){j[g]=d;\n"
"a=true\n"
"}else{h=d\n"
"}}else{if(h-j[g]==1){h--;\n"
"if(!a&&i(g,h)){a=true\n"
"}break\n"
"}else{if(!a&&i(g,h)){a=true\n"
"}break\n"
"}}}if(!a){return null\n"
"}}return j.join(\",\");\n"
"\n"
"},dummy1:0}\n"
"}PluginDetect.onDetectionDone=function(g,e,d,a){\n"
"return -1\n"
"};\n"
"PluginDetect.onWindowLoaded=function(c){\n"
"var b=PluginDetect,a=window;\n"
"if(b.EventWinLoad===true){}else{b.winLoaded=false;\n"
"b.EventWinLoad=true;\n"
"if(typeof a.addEventListener!=\"undefined\"){a.addEventListener(\"load\",b.runFuncs,false)\n"
"}else{if(typeof a.attachEvent!=\"undefined\"){a.attachEvent(\"onload\",b.runFuncs)\n"
"}else{if(typeof a.onload==\"function\"){b.funcs[b.funcs.length]=a.onload\n"
"}a.onload=b.runFuncs\n"
"}}}if(typeof c==\"function\"){b.funcs[b.funcs.length]=c\n"
"}\n"
"};\n"
";\n"
"PluginDetect.funcs=[0];\n"
"PluginDetect.runFuncs=function(){var b=PluginDetect,a;\n"
"b.winLoaded=true;\n"
"for(a=0;\n"
"a<b.funcs.length;\n"
"a++){if(typeof b.funcs[a]==\"function\"){b.funcs[a](b);\n"
"b.funcs[a]=null\n"
"}}};\n"
";\n"
"PluginDetect.quicktime={mimeType:[\"video/quicktime\",\"application/x-quicktimeplayer\",\"image/x-macpaint\",\"image/x-quicktime\"],progID:\"QuickTimeCheckObject.QuickTimeCheck.1\",progID0:\"QuickTime.QuickTime\",classID:\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\",minIEver:7,HTML:'<param name=\"src\" value=\"A14999.mov\" /><param name=\"controller\" value=\"false\" />',getCodeBaseVersion:function(a){return'codebase=\"#version='+a+'\"'\n"
"},digits:[8,64,16,0],clipTo3digits:function(f){if(f===null||typeof f==\"undefined\"){return null\n"
"}var e,d,h,g=this.$;\n"
"e=f.split(\",\");\n"
"if(g.compareNums(f,\"7,60,0,0\")<0&&g.compareNums(f,\"7,50,0,0\")>=0){d=e[0]+\",\"+e[1].charAt(0)+\",\"+e[1].charAt(1)+\",\"+e[2]\n"
"}else{d=e[0]+\",\"+e[1]+\",\"+e[2]+\",\"+e[3]\n"
"}h=d.split(\",\");\n"
"return h[0]+\",\"+h[1]+\",\"+h[2]+\",0\"\n"
"},getVersion:function(){var a=null,d,b=this.$,e=true;\n"
"if(!b.isIE){if(navigator.platform&&(/linux/i).test(navigator.platform)){e=false\n"
"}if(e){d=b.findNavPlugin([\"QuickTime\",\"(Plug-in|Plugin)\"]);\n"
"if(d&&d.name&&b.hasMimeType(this.mimeType)){a=b.getNum(d.name)\n"
"}}this.installed=a?1:-1\n"
"}else{var c;\n"
"if(b.IEver>=this.minIEver&&b.getAXO(this.progID0,1)){a=b.codebaseSearch()\n"
"}else{c=b.getAXO(this.progID);\n"
"if(c&&c.QuickTimeVersion){a=c.QuickTimeVersion.toString(16);\n"
"a=a.charAt(0)+\".\"+a.charAt(1)+\".\"+a.charAt(2)\n"
"}}this.installed=a?1:(b.getAXO(this.progID0,1)?0:-1)\n"
"}this.version=this.clipTo3digits(b.formatNum(a))\n"
"}};\n"
";\n"
"PluginDetect.java={mimeType:\"application/x-java-applet\",classID:\"clsid:8AD9C840-044E-11D1-B3E9-00805F499D93\",DTKclassID:\"clsid:CAFEEFAC-DEC7-0000-0000-ABCDEFFEDCBA\",DTKmimeType:\"application/npruntime-scriptable-plugin;DeploymentToolkit\",JavaVersions:[[1,9,2,25],[1,8,2,25],[1,7,2,25],[1,6,2,25],[1,5,2,25],[1,4,2,25],[1,3,1,25]],searchJavaPluginAXO:function(){var h=null,a=this,c=a.$,g=[],j=[1,5,0,14],i=[1,6,0,2],f=[1,3,1,0],e=[1,4,2,0],d=[1,5,0,7],b=false;\n"
"if(!c.ActiveXEnabled){return null\n"
"};\n"
"b=true;\n"
";\n"
"if(c.IEver>=a.minIEver){g=a.searchJavaAXO(i,i,b);\n"
"if(g.length>0&&b){g=a.searchJavaAXO(j,j,b)\n"
"}}else{\n"
"if(b){g=a.searchJavaAXO(d,d,true)\n"
"};\n"
"if(g.length==0){g=a.searchJavaAXO(f,e,false)\n"
"}}if(g.length>0){h=g[0]\n"
"}a.JavaPlugin_versions=[].concat(g);\n"
"return h\n"
"},searchJavaAXO:function(l,i,m){var n,f,h=this.$,p,k,a,e,g,j,b,q=[];\n"
"if(h.compareNums(l.join(\",\"),i.join(\",\"))>0){i=l\n"
"}i=h.formatNum(i.join(\",\"));\n"
"var o,d=\"1,4,2,0\",c=\"JavaPlugin.\"+l[0]+\"\"+l[1]+\"\"+l[2]+\"\"+(l[3]>0?(\"_\"+(l[3]<10?\"0\":\"\")+l[3]):\"\");\n"
"for(n=0;\n"
"n<this.JavaVersions.length;\n"
"n++){f=this.JavaVersions[n];\n"
"p=\"JavaPlugin.\"+f[0]+\"\"+f[1];\n"
"g=f[0]+\".\"+f[1]+\".\";\n"
"for(a=f[2];\n"
"a>=0;\n"
"a--){b=\"JavaWebStart.isInstalled.\"+g+a+\".0\";\n"
"if(h.compareNums(f[0]+\",\"+f[1]+\",\"+a+\",0\",i)>=0&&!h.getAXO(b,1)){continue\n"
"}o=h.compareNums(f[0]+\",\"+f[1]+\",\"+a+\",0\",d)<0?true:false;\n"
"for(e=f[3];\n"
"e>=0;\n"
"e--){k=a+\"_\"+(e<10?\"0\"+e:e);\n"
"j=p+k;\n"
"if(h.getAXO(j,1)&&(o||h.getAXO(b,1))){q[q.length]=g+k;\n"
"if(!m){return q\n"
"}}if(j==c){return q\n"
"}}if(h.getAXO(p+a,1)&&(o||h.getAXO(b,1))){q[q.length]=g+a;\n"
"if(!m){return q\n"
"}}if(p+a==c){return q\n"
"}}}return q\n"
"},minIEver:7,getFromMimeType:function(a){var h,f,c=this.$,j=new RegExp(a),d,k,i={},e=0,b,g=[\"\"];\n"
"for(h=0;\n"
"h<navigator.mimeTypes.length;\n"
"h++){k=navigator.mimeTypes[h];\n"
"if(j.test(k.type)&&k.enabledPlugin){k=k.type.substring(k.type.indexOf(\"=\")+1,k.type.length);\n"
"d=\"a\"+c.formatNum(k);\n"
"if(typeof i[d]==\"undefined\"){i[d]=k;\n"
"e++\n"
"}}}for(f=0;\n"
"f<e;\n"
"f++){b=\"0,0,0,0\";\n"
"for(h in i){if(i[h]){d=h.substring(1,h.length);\n"
"if(c.compareNums(d,b)>0){b=d\n"
"}}}g[f]=i[\"a\"+b];\n"
"i[\"a\"+b]=null\n"
"}if(!(/windows|macintosh/i).test(navigator.userAgent)){g=[g[0]]\n"
"}return g\n"
"},queryJavaHandler:function(){var b=PluginDetect.java,a=window.java,c;\n"
"b.hasRun=true;\n"
"try{if(typeof a.lang!=\"undefined\"&&typeof a.lang.System!=\"undefined\"){b.value=[a.lang.System.getProperty(\"java.version\")+\" \",a.lang.System.getProperty(\"java.vendor\")+\" \"]\n"
"}}catch(c){}},queryJava:function(){var c=this,d=c.$,b=navigator.userAgent,f;\n"
"if(typeof window.java!=\"undefined\"&&navigator.javaEnabled()&&!c.hasRun){if(d.isGecko){if(d.hasMimeType(\"application/x-java-vm\")){try{var g=document.createElement(\"div\"),a=document.createEvent(\"HTMLEvents\");\n"
"a.initEvent(\"focus\",false,true);\n"
"g.addEventListener(\"focus\",c.queryJavaHandler,false);\n"
"g.dispatchEvent(a)\n"
"}catch(f){}if(!c.hasRun){c.queryJavaHandler()\n"
"}}}else{if((/opera.9\.(0|1)/i).test(b)&&(/mac/i).test(b)){}else{if(!c.hasRun){c.queryJavaHandler()\n"
"}}}}return c.value\n"
"},forceVerifyTag:[],jar:[],VENDORS:[\"Sun Microsystems Inc.\",\"Apple Computer, Inc.\"],init:function(){var a=this,b=a.$;\n"
"if(typeof a.app!=\"undefined\"){a.delJavaApplets(b)\n"
"}a.hasRun=false;\n"
"a.value=[null,null];\n"
"a.useTag=[2,2,2];\n"
"a.app=[0,0,0,0,0,0];\n"
"a.appi=3;\n"
"a.queryDTKresult=null;\n"
"a.OTF=0;\n"
"a.BridgeResult=[[null,null],[null,null],[null,null]];\n"
"a.JavaActive=[0,0,0];\n"
"a.All_versions=[];\n"
"a.DeployTK_versions=[];\n"
"a.MimeType_versions=[];\n"
"a.JavaPlugin_versions=[];\n"
"a.funcs=[];\n"
"var c=a.NOTF;\n"
"if(c){c.$=b;\n"
"if(c.javaInterval){clearInterval(c.javaInterval)\n"
"}c.EventJavaReady=null;\n"
"c.javaInterval=null;\n"
"c.count=0;\n"
"c.intervalLength=250;\n"
"c.countMax=40\n"
"}a.lateDetection=b.winLoaded;\n"
"if(!a.lateDetection){b.onWindowLoaded(a.delJavaApplets)\n"
"}},getVersion:function(f,l){var h,d=this,g=d.$,j=null,n=null,e=null,c=navigator.javaEnabled();\n"
"if(d.getVersionDone===null){d.init()\n"
"}var k;\n"
"if(typeof l!=\"undefined\"&&l.constructor==Array){for(k=0;\n"
"k<d.useTag.length;\n"
"k++){if(typeof l[k]==\"number\"){d.useTag[k]=l[k]\n"
"}}}for(k=0;\n"
"k<d.forceVerifyTag.length;\n"
"k++){d.useTag[k]=d.forceVerifyTag[k]\n"
"}if(typeof f!=\"undefined\"){d.jar[d.jar.length]=f\n"
"}if(d.getVersionDone==0){if(!d.version||d.useAnyTag()){h=d.queryExternalApplet(f);\n"
"if(h[0]){e=h[0];\n"
"n=h[1]\n"
"}}d.EndGetVersion(e,n);\n"
"return\n"
"}var i=d.queryDeploymentToolKit();\n"
"if(typeof i==\"string\"&&i.length>0){j=i;\n"
"n=d.VENDORS[0]\n"
"}if(!g.isIE){var q,m,b,o,a;\n"
"a=g.hasMimeType(d.mimeType);\n"
"o=(a&&c)?true:false;\n"
"if(d.MimeType_versions.length==0&&a){h=d.getFromMimeType(\"application/x-java-applet.*jpi-version.*=\");\n"
"if(h[0]!=\"\"){if(!j){j=h[0]\n"
"}d.MimeType_versions=h\n"
"}}if(!j&&a){h=\"Java[^\\d]*Plug-in\";\n"
"b=g.findNavPlugin(h);\n"
"if(b){h=new RegExp(h,\"i\");\n"
"q=h.test(b.description)?g.getNum(b.description):null;\n"
"m=h.test(b.name)?g.getNum(b.name):null;\n"
"if(q&&m){j=(g.compareNums(g.formatNum(q),g.formatNum(m))>=0)?q:m\n"
"}else{j=q||m\n"
"}}}if(!j&&a&&(/macintosh.*safari/i).test(navigator.userAgent)){b=g.findNavPlugin(\"Java.*\\d.*Plug-in.*Cocoa\",false);\n"
"if(b){q=g.getNum(b.description);\n"
"if(q){j=q\n"
"}}}if(j){d.version0=j;\n"
"if(c){e=j\n"
"}}if(!e||d.useAnyTag()){b=d.queryExternalApplet(f);\n"
"if(b[0]){e=b[0];\n"
"n=b[1]\n"
"}}if(!e){b=d.queryJava();\n"
"if(b[0]){d.version0=b[0];\n"
"e=b[0];\n"
"n=b[1];\n"
"if(d.installed==-0.5){d.installed=0.5\n"
"}}}if(d.installed===null&&!e&&o&&!(/macintosh.*ppc/i).test(navigator.userAgent)){h=d.getFromMimeType(\"application/x-java-applet.*version.*=\");\n"
"if(h[0]!=\"\"){e=h[0]\n"
"}}if(!e&&o){if(/macintosh.*safari/i.test(navigator.userAgent)){if(d.installed===null){d.installed=0\n"
"}else{if(d.installed==-0.5){d.installed=0.5\n"
"}}}}}else{if(!j&&i!=-1){j=d.searchJavaPluginAXO();\n"
"if(j){n=d.VENDORS[0]\n"
"}}if(!j){d.JavaFix()\n"
"}if(j){d.version0=j;\n"
"if(c&&g.ActiveXEnabled){e=j\n"
"}}if(!e||d.useAnyTag()){h=d.queryExternalApplet(f);\n"
"if(h[0]){e=h[0];\n"
"n=h[1]\n"
"}}}if(d.installed===null){d.installed=e?1:(j?-0.2:-1)\n"
"}d.EndGetVersion(e,n)\n"
"},EndGetVersion:function(b,d){var a=this,c=a.$;\n"
"if(a.version0){a.version0=c.formatNum(c.getNum(a.version0))\n"
"}if(b){a.version=c.formatNum(c.getNum(b));\n"
"a.vendor=(typeof d==\"string\"?d:\"\")\n"
"}if(a.getVersionDone!=1){a.getVersionDone=0\n"
"}},queryDeploymentToolKit:function(){var d=this,g=d.$,i,b,h=null,a=null;\n"
"if((g.isGecko&&g.compareNums(g.GeckoRV,g.formatNum(\"1.6\"))<=0)||g.isSafari||(g.isIE&&!g.ActiveXEnabled)){d.queryDTKresult=0\n"
"}if(d.queryDTKresult!==null){return d.queryDTKresult\n"
"}if(g.isIE&&g.IEver>=6){d.app[0]=g.instantiate(\"object\",[],[]);\n"
"h=g.getObject(d.app[0])\n"
"}else{if(!g.isIE&&g.hasMimeType(d.DTKmimeType)){d.app[0]=g.instantiate(\"object\",[\"type\",d.DTKmimeType],[]);\n"
"h=g.getObject(d.app[0])\n"
"}}if(h){if(g.isIE&&g.IEver>=6){try{h.classid=d.DTKclassID\n"
"}catch(i){}}try{var c,f=h.jvms;\n"
"if(f){a=f.getLength();\n"
"if(typeof a==\"number\"){for(b=0;\n"
"b<a;\n"
"b++){c=f.get(a-1-b);\n"
"if(c){c=c.version;\n"
"if(g.getNum(c)){d.DeployTK_versions[b]=c\n"
"}}}}}}catch(i){}}g.hideObject(h);\n"
"d.queryDTKresult=d.DeployTK_versions.length>0?d.DeployTK_versions[0]:(a==0?-1:0);\n"
"return d.queryDTKresult\n"
"},queryExternalApplet:function(d){var c=this,e=c.$,h=c.BridgeResult,b=c.app,g=c.appi,a=\"&nbsp;&nbsp;&nbsp;&nbsp;\";\n"
"if(typeof d!=\"string\"||!(/\.jar\s*$/).test(d)){return[null,null]\n"
"}if(c.OTF<1){c.OTF=1\n"
"}if(!e.isIE){if((e.isGecko||e.isChrome)&&!e.hasMimeType(c.mimeType)&&!c.queryJava()[0]){return[null,null]\n"
"}}if(c.OTF<2){c.OTF=2\n"
"}if(!b[g]&&c.canUseObjectTag()&&c.canUseThisTag(0)){b[1]=e.instantiate(\"object\",[],[],a);\n"
"b[g]=e.isIE?e.instantiate(\"object\",[\"archive\",d,\"code\",\"A.class\",\"type\",c.mimeType],[\"archive\",d,\"code\",\"A.class\",\"mayscript\",\"true\",\"scriptable\",\"true\"],a):e.instantiate(\"object\",[\"archive\",d,\"classid\",\"java:A.class\",\"type\",c.mimeType],[\"archive\",d,\"mayscript\",\"true\",\"scriptable\",\"true\"],a);\n"
"h[0]=[0,0];\n"
"c.query1Applet(g)\n"
"}if(!b[g+1]&&c.canUseAppletTag()&&c.canUseThisTag(1)){b[g+1]=e.instantiate(\"applet\",[\"archive\",d,\"code\",\"A.class\",\"alt\",a,\"mayscript\",\"true\"],[\"mayscript\",\"true\"],a);\n"
"h[1]=[0,0];\n"
"c.query1Applet(g+1)\n"
"}if(e.isIE&&!b[g+2]&&c.canUseObjectTag()&&c.canUseThisTag(2)){b[g+2]=e.instantiate(\"object\",[\"classid\",c.classID],[\"archive\",d,\"code\",\"A.class\",\"mayscript\",\"true\",\"scriptable\",\"true\"],a);\n"
"h[2]=[0,0];\n"
"c.query1Applet(g+2)\n"
"};\n"
"var j,f=0;\n"
"for(j=0;\n"
"j<h.length;\n"
"j++){if(b[g+j]||c.canUseThisTag(j)){f++\n"
"}else{break\n"
"}}if(f==h.length){c.getVersionDone=1;\n"
"if(c.forceVerifyTag.length>0){c.getVersionDone=0\n"
"}}return c.getBR()\n"
"},canUseAppletTag:function(){return((!this.$.isIE||navigator.javaEnabled())?true:false)\n"
"},canUseObjectTag:function(){return((!this.$.isIE||this.$.ActiveXEnabled)?true:false)\n"
"},useAnyTag:function(){var b=this,a;\n"
"for(a=0;\n"
"a<b.useTag.length;\n"
"a++){if(b.canUseThisTag(a)){return true\n"
"}}return false\n"
"},canUseThisTag:function(c){var a=this,b=a.$;\n"
"if(a.useTag[c]==3){return true\n"
"}if(!a.version0||!navigator.javaEnabled()||(b.isIE&&!b.ActiveXEnabled)){if(a.useTag[c]==2){return true\n"
"}if(a.useTag[c]==1&&!a.getBR()[0]){return true\n"
"}}return false\n"
"},getBR:function(){var b=this.BridgeResult,a;\n"
"for(a=0;\n"
"a<b.length;\n"
"a++){if(b[a][0]){return[b[a][0],b[a][1]]\n"
"}}return[b[0][0],b[0][1]]\n"
"},delJavaApplets:function(b){var c=b.java.app,a;\n"
"for(a=c.length-1;\n"
"a>=0;\n"
"a--){b.uninstantiate(c[a])\n"
"}},query1Applet:function(g){var f,c=this,d=c.$,a=null,h=null,b=d.getObject(c.app[g],true);\n"
"try{if(b){a=b.getVersion()+\" \";\n"
"h=b.getVendor()+\" \";\n"
"if(d.num(a)){c.BridgeResult[g-c.appi]=[a,h];\n"
"d.hideObject(c.app[g])\n"
"}if(d.isIE&&a&&b.readyState!=4){d.garbage=true;\n"
"d.uninstantiate(c.app[g])\n"
"}}}catch(f){}},NOTF:{isJavaActive:function(){\n"
"}},append:function(e,d){for(var c=0;\n"
"c<d.length;\n"
"c++){e[e.length]=d[c]\n"
"}},getInfo:function(){var m={};\n"
";\n"
"var a=this,d=a.$,h,l=a.installed;\n"
"m={All_versions:[],DeployTK_versions:[],MimeType_versions:[],DeploymentToolkitPlugin:(a.queryDTKresult==0?false:true),vendor:(typeof a.vendor==\"string\"?a.vendor:\"\"),OTF:(a.OTF<3?0:(a.OTF==3?1:2))};\n"
"var g=[null,null,null];\n"
"for(h=0;\n"
"h<a.BridgeResult.length;\n"
"h++){g[h]=a.BridgeResult[h][0]?1:(a.JavaActive[h]==1?0:(a.useTag[h]>=1&&a.OTF>=1&&a.OTF!=3&&!(h==2&&!d.isIE)&&(a.BridgeResult[h][0]!==null||(h==1&&!a.canUseAppletTag())||(h!=1&&!a.canUseObjectTag())||l==-0.2||l==-1)?-1:null))\n"
"}m.objectTag=g[0];\n"
"m.appletTag=g[1];\n"
"m.objectTagActiveX=g[2];\n"
"var c=m.All_versions,k=m.DeployTK_versions,f=m.MimeType_versions,b=a.JavaPlugin_versions;\n"
"a.append(k,a.DeployTK_versions);\n"
"a.append(f,a.MimeType_versions);\n"
"a.append(c,(k.length>0?k:(f.length>0?f:(b.length>0?b:(typeof a.version==\"string\"?[a.version]:[])))));\n"
"for(h=0;\n"
"h<c.length;\n"
"h++){c[h]=d.formatNum(d.getNum(c[h]))\n"
"}var i,e=null;\n"
"if(!d.isIE){i=f.length>0?d.hasMimeType(a.mimeType+\";jpi-version=\"+f[0]):d.hasMimeType(a.mimeType);\n"
"if(i){e=i.enabledPlugin\n"
"}}m.name=e?e.name:\"\";\n"
"m.description=e?e.description:\"\";\n"
"var j=null;\n"
"if((l==0||l==1)&&m.vendor==\"\"){if(/macintosh/i.test(navigator.userAgent)){j=a.VENDORS[1]\n"
"}else{if(!d.isIE&&(/windows/i).test(navigator.userAgent)){j=a.VENDORS[0]\n"
"}else{if(/linux/i.test(navigator.userAgent)){j=a.VENDORS[0]\n"
"}}}if(j){m.vendor=j\n"
"}};\n"
"return m\n"
"},JavaFix:function(){}};\n"
";\n"
"PluginDetect.devalvr={mimeType:\"application/x-devalvrx\",progID:\"DevalVRXCtrl.DevalVRXCtrl.1\",classID:\"clsid:5D2CF9D0-113A-476B-986F-288B54571614\",getVersion:function(){var a=null,g,c=this.$,f;\n"
"if(!c.isIE){g=c.findNavPlugin(\"DevalVR\");\n"
"if(g&&g.name&&c.hasMimeType(this.mimeType)){a=g.description.split(\" \")[3]\n"
"}this.installed=a?1:-1\n"
"}else{var b,h,d;\n"
"h=c.getAXO(this.progID,1);\n"
"if(h){b=c.instantiate(\"object\",[\"classid\",this.classID],[\"src\",\"\"]);\n"
"d=c.getObject(b);\n"
"if(d){try{if(d.pluginversion){a=\"00000000\"+d.pluginversion.toString(16);\n"
"a=a.substr(a.length-8,8);\n"
"a=parseInt(a.substr(0,2),16)+\",\"+parseInt(a.substr(2,2),16)+\",\"+parseInt(a.substr(4,2),16)+\",\"+parseInt(a.substr(6,2),16)\n"
"}}catch(f){}}c.uninstantiate(b)\n"
"}this.installed=a?1:(h?0:-1)\n"
"}this.version=c.formatNum(a)\n"
"}};\n"
";\n"
"PluginDetect.flash={mimeType:[\"application/x-shockwave-flash\",\"application/futuresplash\"],progID:\"ShockwaveFlash.ShockwaveFlash\",classID:\"clsid:D27CDB6E-AE6D-11CF-96B8-444553540000\",getVersion:function(){var c=function(i){if(!i){return null\n"
"}var e=/[\d][\d\,\.\s]*[rRdD]{0,1}[\d\,]*/.exec(i);\n"
"return e?e[0].replace(/[rRdD\.]/g,\",\").replace(/\s/g,\"\"):null\n"
"};\n"
"var j,g=this.$,h,f,b=null,a=null,d=null;\n"
"if(!g.isIE){j=g.findNavPlugin(\"Flash\");\n"
"if(j&&j.description&&g.hasMimeType(this.mimeType)){b=c(j.description)\n"
"}}else{for(f=15;\n"
"f>2;\n"
"f--){a=g.getAXO(this.progID+\".\"+f);\n"
"if(a){d=f.toString();\n"
"break\n"
"}}if(d==\"6\"){try{a.AllowScriptAccess=\"always\"\n"
"}catch(h){return\"6,0,21,0\"\n"
"}}try{b=c(a.GetVariable(\"$version\"))\n"
"}catch(h){}if(!b&&d){b=d\n"
"}}this.installed=b?1:-1;\n"
"this.version=g.formatNum(b);\n"
"return true\n"
"}};\n"
";\n"
"PluginDetect.shockwave={mimeType:\"application/x-director\",progID:\"SWCtl.SWCtl\",classID:\"clsid:166B1BCA-3F9C-11CF-8075-444553540000\",getVersion:function(){var a=null,b=null,f,d,c=this.$;\n"
"if(!c.isIE){d=c.findNavPlugin(\"Shockwave for Director\");\n"
"if(d&&d.description&&c.hasMimeType(this.mimeType)){a=c.getNum(d.description)\n"
"}}else{try{b=c.getAXO(this.progID).ShockwaveVersion(\"\")\n"
"}catch(f){}if(typeof b==\"string\"&&b.length>0){a=c.getNum(b)\n"
"}else{if(c.getAXO(this.progID+\".8\",1)){a=\"8\"\n"
"}else{if(c.getAXO(this.progID+\".7\",1)){a=\"7\"\n"
"}else{if(c.getAXO(this.progID+\".1\",1)){a=\"6\"\n"
"}}}}}this.installed=a?1:-1;\n"
"this.version=c.formatNum(a)\n"
"}};\n"
";\n"
"PluginDetect.div=null;\n"
"PluginDetect.pluginSize=1;\n"
"PluginDetect.DOMbody=null;\n"
"PluginDetect.uninstantiate=function(a){var c,b=this;\n"
"if(!a){return\n"
"}try{if(a[0]&&a[0].firstChild){a[0].removeChild(a[0].firstChild)\n"
"}if(a[0]&&b.div){b.div.removeChild(a[0])\n"
"}if(b.div&&b.div.childNodes.length==0){b.div.parentNode.removeChild(b.div);\n"
"b.div=null;\n"
"if(b.DOMbody&&b.DOMbody.parentNode){b.DOMbody.parentNode.removeChild(b.DOMbody)\n"
"}b.DOMbody=null\n"
"}a[0]=null\n"
"}catch(c){}};\n"
"PluginDetect.getObject=function(b,a){var f,c=this,d=null;\n"
"try{if(b&&b[0]&&b[0].firstChild){d=b[0].firstChild\n"
"}}catch(f){}try{if(a&&d&&typeof d.focus!=\"undefined\"&&typeof document.hasFocus!=\"undefined\"&&!document.hasFocus()){d.focus()\n"
"}}catch(f){}return d\n"
"};\n"
"PluginDetect.getContainer=function(a){var c,b=null;\n"
"if(a&&a[0]){b=a[0]\n"
"}return b\n"
"};\n"
"PluginDetect.hideObject=function(a){var b=this.getObject(a);\n"
"if(b&&b.style){b.style.height=\"0\"\n"
"}};\n"
"PluginDetect.instantiate=function(h,b,c,a){var j=function(d){var e=d.style;\n"
"if(!e){return\n"
"}e.border=\"0px\";\n"
"e.padding=\"0px\";\n"
"e.margin=\"0px\";\n"
"e.fontSize=(g.pluginSize+3)+\"px\";\n"
"e.height=(g.pluginSize+3)+\"px\";\n"
"e.visibility=\"visible\";\n"
"if(d.tagName&&d.tagName.toLowerCase()==\"div\"){e.width=\"100%\";\n"
"e.display=\"block\"\n"
"}else{if(d.tagName&&d.tagName.toLowerCase()==\"span\"){e.width=g.pluginSize+\"px\";\n"
"e.display=\"inline\"\n"
"}}};\n"
"var k,l=document,g=this,p,i=(l.getElementsByTagName(\"body\")[0]||l.body),o=l.createElement(\"span\"),n,f,m=\"/\";\n"
"if(typeof a==\"undefined\"){a=\"\"\n"
"}p=\"<\"+h+' width=\"'+g.pluginSize+'\" height=\"'+g.pluginSize+'\" ';\n"
"for(n=0;\n"
"n<b.length;\n"
"n=n+2){p+=b[n]+'=\"'+b[n+1]+'\" '\n"
"}p+=\">\";\n"
"for(n=0;\n"
"n<c.length;\n"
"n=n+2){p+='<param name=\"'+c[n]+'\" value=\"'+c[n+1]+'\" />'\n"
"}p+=a+\"<\"+m+h+\">\";\n"
"if(!g.div){g.div=l.createElement(\"div\");\n"
"f=l.getElementById(\"plugindetect\");\n"
"if(f){j(f);\n"
"f.appendChild(g.div)\n"
"}else{if(i){try{if(i.firstChild&&typeof i.insertBefore!=\"undefined\"){i.insertBefore(g.div,i.firstChild)\n"
"}else{i.appendChild(g.div)\n"
"}}catch(k){}}else{try{l.write('<div id=\"pd33993399\">o<'+m+\"div>\");\n"
"i=(l.getElementsByTagName(\"body\")[0]||l.body);\n"
"i.appendChild(g.div);\n"
"i.removeChild(l.getElementById(\"pd33993399\"))\n"
"}catch(k){try{g.DOMbody=l.createElement(\"body\");\n"
"l.getElementsByTagName(\"html\")[0].appendChild(g.DOMbody);\n"
"g.DOMbody.appendChild(g.div)\n"
"}catch(k){}}}}j(g.div)\n"
"}if(g.div&&g.div.parentNode&&g.div.parentNode.parentNode){g.div.appendChild(o);\n"
"try{o.innerHTML=p\n"
"}catch(k){}j(o);\n"
"return[o]\n"
"}return[null]\n"
"};\n"
";\n"
"PluginDetect.windowsmediaplayer={mimeType:[\"application/x-mplayer2\",\"application/asx\"],progID:\"wmplayer.ocx\",classID:\"clsid:6BF52A52-394A-11D3-B153-00C04F79FAA6\",getVersion:function(){var a=null,e=this.$,b=null;\n"
"this.installed=-1;\n"
"if(!e.isIE){if(e.hasMimeType(this.mimeType)){if(e.findNavPlugin([\"Windows\",\"Media\",\"(Plug-in|Plugin)\"],false)||e.findNavPlugin([\"Flip4Mac\",\"Windows\",\"Media\"],false)){this.installed=0\n"
"}var d=e.isGecko&&e.compareNums(e.GeckoRV,e.formatNum(\"1.8\"))<0;\n"
"if(!d&&e.findNavPlugin([\"Windows\",\"Media\",\"Firefox Plugin\"],false)){var c=e.instantiate(\"object\",[\"type\",this.mimeType[0]],[]),f=e.getObject(c);\n"
"if(f){a=f.versionInfo\n"
"}e.uninstantiate(c)\n"
"}}}else{b=e.getAXO(this.progID);\n"
"if(b){a=b.versionInfo\n"
"}}if(a){this.installed=1\n"
"}this.version=e.formatNum(a)\n"
"}};\n"
";\n"
"PluginDetect.silverlight={mimeType:\"application/x-silverlight\",progID:\"AgControl.AgControl\",digits:[9,20,9,12,31],getVersion:function(){var c=this.$,j=document,g=null,b=null,f=false;\n"
"if(!c.isIE){var a=[null,null],e=c.findNavPlugin(\"Silverlight Plug-in\",false),h=c.isGecko&&c.compareNums(c.GeckoRV,c.formatNum(\"1.6\"))<=0;\n"
"if(e&&c.hasMimeType(this.mimeType)){g=c.formatNum(e.description);\n"
"if(g){p=g.split(\",\");\n"
"if(parseInt(p[2],10)>=30226&&parseInt(p[0],10)<2){p[0]=\"2\"\n"
"}g=p.join(\",\")\n"
"}if(c.isGecko&&!h){f=true\n"
"}if(!f&&!h&&g){a=c.instantiate(\"object\",[\"type\",this.mimeType],[]);\n"
"b=c.getObject(a);\n"
"if(b){if(typeof b.IsVersionSupported!=\"undefined\"){f=true\n"
"}if(!f){b.data=\"data:\"+this.mimeType+\",\";\n"
"if(typeof b.IsVersionSupported!=\"undefined\"){f=true\n"
"}}}c.uninstantiate(a)\n"
"}}}else{b=c.getAXO(this.progID);\n"
"var p=[1,0,1,1,1],l,k,o,i=function(d){return(d<10?\"0\":\"\")+d.toString()\n"
"},m=function(q,d,s,t,r){return(q+\".\"+d+\".\"+s+i(t)+i(r)+\".0\")\n"
"},n=function(d,s){var q,r=m((d==0?s:p[0]),(d==1?s:p[1]),(d==2?s:p[2]),(d==3?s:p[3]),(d==4?s:p[4]));\n"
"try{return b.IsVersionSupported(r)\n"
"}catch(q){}return false\n"
"};\n"
"if(b&&typeof b.IsVersionSupported!=\"undefined\"){for(l=0;\n"
"l<this.digits.length;\n"
"l++){o=p[l];\n"
"for(k=o+(l==0?0:1);\n"
"k<=this.digits[l];\n"
"k++){if(n(l,k)){f=true;\n"
"p[l]=k\n"
"}else{break\n"
"}}if(!f){break\n"
"}}if(f){g=m(p[0],p[1],p[2],p[3],p[4])\n"
"}}}this.installed=f?1:-1;\n"
"this.version=c.formatNum(g)\n"
"}};\n"
";\n"
"PluginDetect.vlc={mimeType:\"application/x-vlc-plugin\",progID:\"VideoLAN.VLCPlugin\",compareNums:function(d,c){var j=d.split(\",\"),h=c.split(\",\"),g,b,a,f,e,i;\n"
"for(g=0;\n"
"g<Math.min(j.length,h.length);\n"
"g++){i=/([\d]+)([a-z]?)/.test(j[g]);\n"
"b=parseInt(RegExp.$1,10);\n"
"f=(g==2&&RegExp.$2.length>0)?RegExp.$2.charCodeAt(0):-1;\n"
"i=/([\d]+)([a-z]?)/.test(h[g]);\n"
"a=parseInt(RegExp.$1,10);\n"
"e=(g==2&&RegExp.$2.length>0)?RegExp.$2.charCodeAt(0):-1;\n"
"if(b!=a){return(b>a?1:-1)\n"
"}if(g==2&&f!=e){return(f>e?1:-1)\n"
"}}return 0\n"
"},getVersion:function(){var b=this.$,d,a=null,c;\n"
"if(!b.isIE){if(b.hasMimeType(this.mimeType)){d=b.findNavPlugin([\"VLC\",\"(Plug-in|Plugin)\"],false);\n"
"if(d&&d.description){a=b.getNum(d.description,\"[\\d][\\d\\.]*[a-z]*\")\n"
"}}this.installed=a?1:-1\n"
"}else{d=b.getAXO(this.progID);\n"
"if(d){try{a=b.getNum(d.VersionInfo,\"[\\d][\\d\\.]*[a-z]*\")\n"
"}catch(c){}}this.installed=d?1:-1\n"
"}this.version=b.formatNum(a)\n"
"}};\n"
";\n"
"PluginDetect.initScript();\n"
"\n"
